version: "3.5"

volumes:
  wiremock-data:
  rabbit-data:

networks:
  parkun:

services:
  parkun_bot:
    container_name: parkun_bot
    networks:
      - parkun
    image: skaborik/parkun_bot
    restart: always
    volumes:
      - ${HOME_FOLDER}/logs:/usr/src/app/logs
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun
      - ${HOME_FOLDER}/deploy/parkun_bot:/tmp/parkun_config
    depends_on:
      - parkun_redis
      - parkun_rabbit

  parkun_sender:
    container_name: parkun_sender
    networks:
      - parkun
    image: skaborik/appeal_sender
    restart: always
    volumes:
      - ${HOME_FOLDER}/logs:/usr/src/app/logs
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun
      - ${HOME_FOLDER}/deploy/appeal_sender:/tmp/sender_config
    depends_on:
      - parkun_browser
      - parkun_rabbit
      - parkun_captcha_solver

  parkun_broadcaster:
    container_name: parkun_broadcaster
    networks:
      - parkun
    image: skaborik/broadcaster
    restart: always
    volumes:
      - ${HOME_FOLDER}/logs:/usr/src/app/logs
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun
      - ${HOME_FOLDER}/deploy/broadcaster:/tmp/broadcaster_config
    depends_on:
      - parkun_rabbit

  parkun_redis:
    container_name: parkun_redis
    image: redis:5.0.7-alpine
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    volumes:
      - ${HOME_FOLDER}/redis_data:/data
      - ${HOME_FOLDER}/deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 16379:6379
    networks:
      - parkun

  parkun_rabbit:
    container_name: parkun_rabbit
    networks:
      - parkun
    ports:
      - 5672:5672
      - 15672:15672
    build:
      context: ${HOME_FOLDER}/deploy/rabbit
      dockerfile: Dockerfile
    volumes:
      - ${HOME_FOLDER}/rabbit_data:/var/lib/rabbitmq
    restart: always

  parkun_browser:
    container_name: parkun_browser
    image: selenium/standalone-firefox:3.141.59
    networks:
      - parkun
    restart: always
    volumes:
      - /dev/shm:/dev/shm

  parkun_captcha_solver:
    container_name: parkun_captcha_solver
    image: skaborik/solver
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0
      - "RUN=flask run --host=0.0.0.0 --port=5000"
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - parkun
    restart: always

  parkun_numberplate:
    container_name: parkun_numberplate
    image: skaborik/numberplate_by
    networks:
      - parkun
    ports:
      - 5001:80
    volumes:
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun
    restart: always
    hostname: parkun_numberplate
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0
      - "RUN=flask run --host=0.0.0.0 --port=80"
    command: flask run --host=0.0.0.0 --port=80
